#!/bin/bash

# ============================================================
# My Toshiba's function buttons don't work in Ubuntu
# This script turns off the touchpad
#
# run script to find the touchpad's ID
# run script with -d(isable) or -e(nable) <ID> to turn on or off
# example:
# ./touchpad
# ./touchpad -d 11
# ============================================================

usage() { echo "Usage: $0 [-d] [-e] <ID>" 1>&2; exit 1; }

# if no options used, input list is displayed
(( $# )) || xinput list

# options are d and e
while getopts ":de" flag; do
    case "${flag}" in

        d) #disable the ID given
            xinput set-prop $2 "Device Enabled" 0
            echo "touchpad is disabled"
        ;;

        e) #enable the ID given
            xinput set-prop $2 "Device Enabled" 1
            echo "touchpad is enabled"
        ;;

        *)
            xinput list
            usage
        ;;
    esac
done
