#!/bin/bash

# ============================================================
# My Toshiba's function buttons don't work in Ubuntu
# This script turns off the touchpad
#
# run script to find the touchpad's ID
# run with the -d(isable) or -e(nable) <ID> to turn on or off
#
# ============================================================

usage() { echo "Usage: $0 [-d] [-e] <ID>" 1>&2; exit 1; }

(( $# )) || xinput list

while getopts ":de" flag; do
    case "${flag}" in

        d)
            xinput set-prop $2 "Device Enabled" 0
            echo "touchpad is disabled"
        ;;

        e)
            xinput set-prop $2 "Device Enabled" 1
            echo "touchpad is enabled"
        ;;

        *)
            xinput list
            usage
        ;;
    esac
done
